schema_version: 1

context:
  version: "0.8.3"

package:
  name: linkbikenet
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/l/linkbikenet/linkbikenet-${{ version }}.tar.gz
  sha256: 4539ff3fd7e83a574cc5b40b65599dbde4e0f6b755852ba5a8c2f3dc8e1d65c2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77.0.3
    - pip
  run:
    - python >=${{ python_min }}
    - geopandas >=1
    - osmnx >=2
    - scipy
    - geojson
    - tqdm

tests:
  - python:
      imports:
        - linkbikenet
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: BikeNetKit Python package to link disconnected bicycle network components
  license: AGPL-3.0-only
  license_file: LICENSE
  homepage: https://bikenetkit.org/linkbikenet/
  documentation: https://docs.bikenetkit.org/LinkBikeNet/
  repository: https://github.com/BikeNetKit/LinkBikeNet/

extra:
  recipe-maintainers:
    - mszell
